services:
  - type: web
    name: axonhub
    runtime: docker
    plan: free
    envVars:
      - key: AXONHUB_SERVER_PORT
        value: 8090
      - key: AXONHUB_DB_DIALECT
        value: postgres
      - key: AXONHUB_DB_DSN
        value: postgresql://postgres.wqbsmokjmmnukdpyxlvx:db1043960000@aws-1-us-east-2.pooler.supabase.com:6543/postgres
      - key: AXONHUB_LOG_LEVEL
        value: info
    healthCheckPath: /health
    autoDeploy: true
